name = "Shopifac"
client_id = "974e44028d8fa5287c173836427343e8"
application_url = "https://shopify-facturante-saas-production-d49a.up.railway.app"
embedded = true

[access_scopes]
scopes = "read_orders,write_orders"

[auth]
redirect_urls = ["https://shopify-facturante-saas-production-d49a.up.railway.app/api/auth/callback"]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = ["orders/paid"]
  uri = "/webhooks/shopify/order-paid"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/shopify/app-uninstalled"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "/webhooks/shopify"

[pos]
embedded = false
