api_version = "2025-04"

[[extensions]]
name = "Campo DNI/CUIT - Shopifac"
handle = "shopifac-checkout-dni"
uid = "915f3fcc-451d-4257-99cb-7bda2f6d66b5"
type = "ui_extension"

[[extensions.targeting]]
target = "purchase.checkout.block.render"
module = "./src/CheckoutDNI.js"

[extensions.capabilities]
api_access = true
