api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "shopifac-checkout-dni"
uid = "915f3fcc-451d-4257-99cb-7bda2f6d66b5"
type = "ui_extension"

[[extensions.targeting]]
target = "purchase.checkout.contact.render-after"
module = "./src/CheckoutDNI.js"

[extensions.settings]
  [[extensions.settings.fields]]
  key = "enable_dni"
  type = "boolean"
  name = "t:settings.enable_dni.name"
  description = "t:settings.enable_dni.description"
