api_version = "2026-01"

[[extensions]]
name = "Generar Factura - Shopifac"
handle = "shopifac-generate-invoice"
uid = "ab4c5b68-d211-c35f-f844-ca51727389819920144d"
type = "ui_extension"

[[extensions.targeting]]
target = "admin.order-details.action.render"
module = "./src/ActionExtension.jsx"

[extensions.capabilities]
api_access = true
network_access = true