api_version = "2025-04"

[[extensions]]
name = "t:name"
handle = "shopifac-generate-invoice"
uid = "ab4c5b68-d211-c35f-f844-ca51727389819920144d"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/ActionExtension.jsx"
target = "admin.order-details.action.render"
